name: Create Release

on:
  push:
    tags:
      - "v*.*.*" # Só roda quando um tag com SemVer for enviado

permissions:
  contents: write # 🔥 Permissão necessária para criar releases

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip archive
        run: |
          zip -r scion-hero-foundry.zip . -x '*.git*' -x '*.github*'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: scion-hero-foundry.zip
        env:
          GITHUB_TOKEN: "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"
